# -*- mode: ruby -*-
# vi: set ft=ruby :

Vagrant.configure("2") do |config|
  config.vm.box = "hashicorp/bionic64"

  # Setup network configuration
  config.vm.define "springboot"
  config.vm.network :private_network, ip: "192.168.111.222"

  # Run Ansible from Vagrant host
  config.vm.provision :ansible do |ansible|
    ansible.playbook = "provisioning/playbook.yml"
  end
end
