apiVersion: v1
kind: Service
metadata:
  name: meowapp
  labels:
    app: meowapp
  namespace: catapp
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30001
      protocol: TCP
  selector:
    app: meowapp
